language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.3.0
- 2.4.1
- 2.5.1
notifications:
  email:
    recipients:
    - alfonso.delgado@viamo.io
    on_success: change
    on_failure: always
script:
- bundle exec rake quick
- gem build sensu-plugins-twilio.gemspec
- gem install sensu-plugins-twilio-*.gem
deploy:
  provider: script
  gem:  bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh sensu-plugins-twilio
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    rvm: 2.3.0
    rvm: 2.4.1
    rvm: 2.5.1
