language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.4.1
notifications:
  email:
    recipients:
    - alfonso.delgado@viamo.io
    on_success: change
    on_failure: always
script:
- bundle exec rake quick
- gem build sensu-plugins-twilio.gemspec
- gem install sensu-plugins-twilio-*.gem
before_deploy:
- bash -c "[ ! -d bonsai/ ] && git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai || echo 'bonsai/ exists, skipping git clone'"
deploy:
  provider: script
  gem:  bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh sensu-plugins-twilio
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1
